package com.tiquionophist.core

import com.tiquionophist.Res
import com.tiquionophist.subject_anatomy
import com.tiquionophist.subject_art
import com.tiquionophist.subject_biology
import com.tiquionophist.subject_bondage
import com.tiquionophist.subject_chemistry
import com.tiquionophist.subject_computer_science
import com.tiquionophist.subject_economics
import com.tiquionophist.subject_english
import com.tiquionophist.subject_geography
import com.tiquionophist.subject_history
import com.tiquionophist.subject_math
import com.tiquionophist.subject_music
import com.tiquionophist.subject_philosophy
import com.tiquionophist.subject_physics
import com.tiquionophist.subject_practical_sex_education
import com.tiquionophist.subject_religion
import com.tiquionophist.subject_school_sport
import com.tiquionophist.subject_swimming
import com.tiquionophist.subject_theoretical_education
import org.jetbrains.compose.resources.DrawableResource
import java.util.EnumSet

/**
 * The set of teachable subjects in the game, each of which has an optional set of [classrooms] where it can be taught
 * (or null if it can be taught anywhere) and set of [stats] generated by students and teachers in the class.
 */
enum class Subject(
    val classrooms: EnumSet<Classroom>? = null,
    val stats: StatSet,
) {
    ANATOMY(
        classrooms = EnumSet.of(Classroom.BIOLOGY),
        stats = StatSet(Stat.AROUSAL to "5.0", Stat.INHIBITION to "-0.1", Stat.LUST to "0.1")
    ),
    ART(
        classrooms = EnumSet.of(Classroom.ART),
        stats = StatSet(Stat.HAPPINESS to "0.5", Stat.INHIBITION to "-0.1")
    ),
    BIOLOGY(
        classrooms = EnumSet.of(Classroom.BIOLOGY),
        stats = StatSet(Stat.AROUSAL to "0.025", Stat.EDUCATION to "0.2")
    ),
    BONDAGE(
        classrooms = EnumSet.of(Classroom.BASEMENT),
        stats = StatSet(
            Stat.AUTHORITY to "0.1",
            Stat.CORRUPTION to "0.3",
            Stat.HAPPINESS to "-0.1",
            Stat.INHIBITION to "-0.2",
            Stat.LOYALTY to "0.1",
            Stat.LUST to "0.15",
            Stat.WILLPOWER to "-0.2",
        )
    ),
    CHEMISTRY(
        classrooms = EnumSet.of(Classroom.CHEMISTRY),
        stats = StatSet(Stat.EDUCATION to "0.1", Stat.INTELLIGENCE to "0.25")
    ),
    COMPUTER_SCIENCE(
        classrooms = EnumSet.of(Classroom.COMPUTER),
        stats = StatSet(Stat.INTELLIGENCE to "0.4")
    ),
    ECONOMICS(
        stats = StatSet(Stat.CORRUPTION to "0.05", Stat.INTELLIGENCE to "0.1")
    ),
    EMPTY(
        stats = StatSet(
            Stat.CORRUPTION to "0.01",
            Stat.EDUCATION to "-0.05",
            Stat.ENERGY to "0.1",
            Stat.HAPPINESS to "0.25",
            Stat.LOYALTY to "-0.025",
        )
    ),
    ENGLISH(
        stats = StatSet(Stat.CHARISMA to "0.1", Stat.HAPPINESS to "0.1")
    ),
    GEOGRAPHY(
        stats = StatSet(Stat.EDUCATION to "0.3")
    ),
    HISTORY(
        stats = StatSet(Stat.EDUCATION to "0.45", Stat.HAPPINESS to "-0.25")
    ),
    MATH(
        stats = StatSet(Stat.INTELLIGENCE to "0.35")
    ),
    MUSIC(
        classrooms = EnumSet.of(Classroom.MUSIC),
        stats = StatSet(Stat.HAPPINESS to "0.3")
    ),
    PHILOSOPHY(
        stats = StatSet(Stat.EDUCATION to "0.1", Stat.INTELLIGENCE to "0.1", Stat.LOYALTY to "0.1")
    ),
    PHYSICS(
        classrooms = EnumSet.of(Classroom.CHEMISTRY),
        stats = StatSet(Stat.INTELLIGENCE to "0.3")
    ),
    PRACTICAL_SEX_EDUCATION(
        stats = StatSet(
            Stat.AROUSAL to "5.0",
            Stat.CORRUPTION to "0.05",
            Stat.HAPPINESS to "0.15",
            Stat.INHIBITION to "-0.2",
            Stat.LUST to "0.2",
            Stat.STAMINA to "0.2",
        )
    ),
    RELIGION(
        stats = StatSet(Stat.CORRUPTION to "-0.05", Stat.LOYALTY to "0.3")
    ),
    SCHOOL_SPORT(
        classrooms = EnumSet.of(Classroom.GYM, Classroom.SPORTS_AREA),
        stats = StatSet(Stat.STAMINA to "0.4", Stat.HAPPINESS to "0.2")
    ),
    SWIMMING(
        classrooms = EnumSet.of(Classroom.SWIMMING_POOL),
        stats = StatSet(Stat.STAMINA to "0.6", Stat.HAPPINESS to "0.1", Stat.CHARISMA to "0.05")
    ),
    THEORETICAL_SEX_EDUCATION(
        stats = StatSet(
            Stat.AROUSAL to "1.0",
            Stat.CORRUPTION to "0.05",
            Stat.INHIBITION to "-0.05",
            Stat.LUST to "0.2",
        )
    ),
    ;

    val imageRes: DrawableResource? by lazy {
        when (this) {
            ANATOMY -> Res.drawable.subject_anatomy
            ART -> Res.drawable.subject_art
            BIOLOGY -> Res.drawable.subject_biology
            BONDAGE -> Res.drawable.subject_bondage
            CHEMISTRY -> Res.drawable.subject_chemistry
            COMPUTER_SCIENCE -> Res.drawable.subject_computer_science
            ECONOMICS -> Res.drawable.subject_economics
            EMPTY -> null
            ENGLISH -> Res.drawable.subject_english
            GEOGRAPHY -> Res.drawable.subject_geography
            HISTORY -> Res.drawable.subject_history
            MATH -> Res.drawable.subject_math
            MUSIC -> Res.drawable.subject_music
            PHILOSOPHY -> Res.drawable.subject_philosophy
            PHYSICS -> Res.drawable.subject_physics
            PRACTICAL_SEX_EDUCATION -> Res.drawable.subject_practical_sex_education
            RELIGION -> Res.drawable.subject_religion
            SCHOOL_SPORT -> Res.drawable.subject_school_sport
            SWIMMING -> Res.drawable.subject_swimming
            THEORETICAL_SEX_EDUCATION -> Res.drawable.subject_theoretical_education
        }
    }
}
